// @ts-check
import { defineConfig } from "astro/config";
import sitemap from "@astrojs/sitemap";
import tailwindcss from "@tailwindcss/vite";

// Set this per client. Used for canonical URLs, sitemap, and OG tags.
const SITE_URL = process.env.SITE_URL ?? "https://hello-client.pages.dev";

export default defineConfig({
  site: SITE_URL,
  integrations: [sitemap()],
  vite: {
    // Tailwind v4 uses a Vite plugin instead of a PostCSS plugin. It reads
    // the `@theme` block from src/styles/tokens.css (generated by the token
    // pipeline) to discover the design system's scales and emit utilities.
    plugins: [tailwindcss()],
  },
  build: {
    inlineStylesheets: "auto",
  },
});
